upstream mesa_fast_web { server mesa_fast_web:80; }
upstream mesa_fast_api { server mesa_fast_api:4545; }

server {
  listen 80;
  server_name mesafast.com www.mesafast.com api.mesafast.com;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / { return 301 https://$host$request_uri; }
}

server {
  listen 443 ssl;
  server_name mesafast.com www.mesafast.com;

  ssl_certificate /etc/letsencrypt/live/mesafast.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/mesafast.com/privkey.pem;

  location / {
    proxy_pass http://mesa_fast_web;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}

server {
  listen 443 ssl;
  server_name api.mesafast.com;

  ssl_certificate /etc/letsencrypt/live/mesafast.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/mesafast.com/privkey.pem;

  location / {
    proxy_pass http://mesa_fast_api;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
